url: "https://koseihabunnko.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "." # the subpath of your site, e.g. /blog
title: "個性派文庫" # the name of your site, e.g. ACME Corp.
lang: "ja-JP"

source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  posts:
    output          : true

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", ".gitignore"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
#markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Plugins
whitelist           : []
plugins             :
  - jekyll-feed
  - jekyll-sitemap
