version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --drafts --future --unpublished --incremental
    volumes:
      - .:/srv/jekyll
      - /srv/jekyll/_site
    ports:
      - "4000:4000"
    environment:
      - JEKYLL_ENV=development